<?php
/**
 * ResponseInfo
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Clainy\OpenxpanApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * XPan NAS API
 *
 * API for accessing XPan NAS data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Clainy\OpenxpanApiClient\Model;

use \ArrayAccess;
use \Clainy\OpenxpanApiClient\ObjectSerializer;

/**
 * ResponseInfo Class Doc Comment
 *
 * @category Class
 * @description 该返回参数已废弃下线，请勿关注; 用户获取文档预览地址。如果接口只下发了docpreview，那么文档预览地址&#x3D;docpreview + \&quot;type&#x3D;pdf&amp;from&#x3D;lo\&quot;。（已下线）; 图片缩略图，包含三个尺寸; 缩略图，包含三个尺寸; 文件大小
 * @package  Clainy\OpenxpanApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ResponseInfo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ResponseInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'category' => 'int',
        '_fs_id' => 'int',
        'isdir' => 'int',
        'local_ctime' => 'int',
        'local_mtime' => 'int',
        'server_ctime' => 'int',
        'server_mtime' => 'int',
        'md5' => 'string',
        'size' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'category' => null,
        '_fs_id' => null,
        'isdir' => null,
        'local_ctime' => null,
        'local_mtime' => null,
        'server_ctime' => null,
        'server_mtime' => null,
        'md5' => null,
        'size' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'category' => false,
		'_fs_id' => false,
		'isdir' => false,
		'local_ctime' => false,
		'local_mtime' => false,
		'server_ctime' => false,
		'server_mtime' => false,
		'md5' => false,
		'size' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'category' => 'category',
        '_fs_id' => ' fs_id',
        'isdir' => 'isdir',
        'local_ctime' => 'local_ctime',
        'local_mtime' => 'local_mtime',
        'server_ctime' => 'server_ctime',
        'server_mtime' => 'server_mtime',
        'md5' => 'md5',
        'size' => 'size'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'category' => 'setCategory',
        '_fs_id' => 'setFsId',
        'isdir' => 'setIsdir',
        'local_ctime' => 'setLocalCtime',
        'local_mtime' => 'setLocalMtime',
        'server_ctime' => 'setServerCtime',
        'server_mtime' => 'setServerMtime',
        'md5' => 'setMd5',
        'size' => 'setSize'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'category' => 'getCategory',
        '_fs_id' => 'getFsId',
        'isdir' => 'getIsdir',
        'local_ctime' => 'getLocalCtime',
        'local_mtime' => 'getLocalMtime',
        'server_ctime' => 'getServerCtime',
        'server_mtime' => 'getServerMtime',
        'md5' => 'getMd5',
        'size' => 'getSize'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('category', $data ?? [], null);
        $this->setIfExists('_fs_id', $data ?? [], null);
        $this->setIfExists('isdir', $data ?? [], null);
        $this->setIfExists('local_ctime', $data ?? [], null);
        $this->setIfExists('local_mtime', $data ?? [], null);
        $this->setIfExists('server_ctime', $data ?? [], null);
        $this->setIfExists('server_mtime', $data ?? [], null);
        $this->setIfExists('md5', $data ?? [], null);
        $this->setIfExists('size', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets category
     *
     * @return int|null
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param int|null $category 文件类型
     *
     * @return self
     */
    public function setCategory($category)
    {
        if (is_null($category)) {
            throw new \InvalidArgumentException('non-nullable category cannot be null');
        }
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets _fs_id
     *
     * @return int|null
     */
    public function getFsId()
    {
        return $this->container['_fs_id'];
    }

    /**
     * Sets _fs_id
     *
     * @param int|null $_fs_id 文件在云端的唯一标识
     *
     * @return self
     */
    public function setFsId($_fs_id)
    {
        if (is_null($_fs_id)) {
            throw new \InvalidArgumentException('non-nullable _fs_id cannot be null');
        }
        $this->container['_fs_id'] = $_fs_id;

        return $this;
    }

    /**
     * Gets isdir
     *
     * @return int|null
     */
    public function getIsdir()
    {
        return $this->container['isdir'];
    }

    /**
     * Sets isdir
     *
     * @param int|null $isdir 是否是目录，0为否，1为是
     *
     * @return self
     */
    public function setIsdir($isdir)
    {
        if (is_null($isdir)) {
            throw new \InvalidArgumentException('non-nullable isdir cannot be null');
        }
        $this->container['isdir'] = $isdir;

        return $this;
    }

    /**
     * Gets local_ctime
     *
     * @return int|null
     */
    public function getLocalCtime()
    {
        return $this->container['local_ctime'];
    }

    /**
     * Sets local_ctime
     *
     * @param int|null $local_ctime 文件在客户端创建时间
     *
     * @return self
     */
    public function setLocalCtime($local_ctime)
    {
        if (is_null($local_ctime)) {
            throw new \InvalidArgumentException('non-nullable local_ctime cannot be null');
        }
        $this->container['local_ctime'] = $local_ctime;

        return $this;
    }

    /**
     * Gets local_mtime
     *
     * @return int|null
     */
    public function getLocalMtime()
    {
        return $this->container['local_mtime'];
    }

    /**
     * Sets local_mtime
     *
     * @param int|null $local_mtime 文件在客户端修改时间
     *
     * @return self
     */
    public function setLocalMtime($local_mtime)
    {
        if (is_null($local_mtime)) {
            throw new \InvalidArgumentException('non-nullable local_mtime cannot be null');
        }
        $this->container['local_mtime'] = $local_mtime;

        return $this;
    }

    /**
     * Gets server_ctime
     *
     * @return int|null
     */
    public function getServerCtime()
    {
        return $this->container['server_ctime'];
    }

    /**
     * Sets server_ctime
     *
     * @param int|null $server_ctime 文件在服务端创建时间
     *
     * @return self
     */
    public function setServerCtime($server_ctime)
    {
        if (is_null($server_ctime)) {
            throw new \InvalidArgumentException('non-nullable server_ctime cannot be null');
        }
        $this->container['server_ctime'] = $server_ctime;

        return $this;
    }

    /**
     * Gets server_mtime
     *
     * @return int|null
     */
    public function getServerMtime()
    {
        return $this->container['server_mtime'];
    }

    /**
     * Sets server_mtime
     *
     * @param int|null $server_mtime 文件在服务端修改时间
     *
     * @return self
     */
    public function setServerMtime($server_mtime)
    {
        if (is_null($server_mtime)) {
            throw new \InvalidArgumentException('non-nullable server_mtime cannot be null');
        }
        $this->container['server_mtime'] = $server_mtime;

        return $this;
    }

    /**
     * Gets md5
     *
     * @return string|null
     */
    public function getMd5()
    {
        return $this->container['md5'];
    }

    /**
     * Sets md5
     *
     * @param string|null $md5 云端哈希（非文件真实MD5）
     *
     * @return self
     */
    public function setMd5($md5)
    {
        if (is_null($md5)) {
            throw new \InvalidArgumentException('non-nullable md5 cannot be null');
        }
        $this->container['md5'] = $md5;

        return $this;
    }

    /**
     * Gets size
     *
     * @return int|null
     */
    public function getSize()
    {
        return $this->container['size'];
    }

    /**
     * Sets size
     *
     * @param int|null $size 文件大小
     *
     * @return self
     */
    public function setSize($size)
    {
        if (is_null($size)) {
            throw new \InvalidArgumentException('non-nullable size cannot be null');
        }
        $this->container['size'] = $size;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


