<?php
/**
 * PostXpanFilePrecreateTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FunEngines\BaiduXpanApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * XPan NAS API
 *
 * API for accessing XPan NAS data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FunEngines\BaiduXpanApiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PostXpanFilePrecreateTest Class Doc Comment
 *
 * @category    Class
 * @description PostXpanFilePrecreate
 * @package     FunEngines\BaiduXpanApiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PostXpanFilePrecreateTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PostXpanFilePrecreate"
     */
    public function testPostXpanFilePrecreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "isdir"
     */
    public function testPropertyIsdir()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "block_list"
     */
    public function testPropertyBlockList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "autoinit"
     */
    public function testPropertyAutoinit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rtype"
     */
    public function testPropertyRtype()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "uploadid"
     */
    public function testPropertyUploadid()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "content_md5"
     */
    public function testPropertyContentMd5()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "slice_md5"
     */
    public function testPropertySliceMd5()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "local_ctime"
     */
    public function testPropertyLocalCtime()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "local_mtime"
     */
    public function testPropertyLocalMtime()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
