<?php
/**
 * ResponseInfoTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FunEngines\BaiduXpanApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * XPan NAS API
 *
 * API for accessing XPan NAS data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FunEngines\BaiduXpanApiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ResponseInfoTest Class Doc Comment
 *
 * @category    Class
 * @description 该返回参数已废弃下线，请勿关注; 用户获取文档预览地址。如果接口只下发了docpreview，那么文档预览地址&#x3D;docpreview + \&quot;type&#x3D;pdf&amp;from&#x3D;lo\&quot;。（已下线）; 图片缩略图，包含三个尺寸; 缩略图，包含三个尺寸; 文件大小
 * @package     FunEngines\BaiduXpanApiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ResponseInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ResponseInfo"
     */
    public function testResponseInfo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "_fs_id"
     */
    public function testPropertyFsId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "isdir"
     */
    public function testPropertyIsdir()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "local_ctime"
     */
    public function testPropertyLocalCtime()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "local_mtime"
     */
    public function testPropertyLocalMtime()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "server_ctime"
     */
    public function testPropertyServerCtime()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "server_mtime"
     */
    public function testPropertyServerMtime()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "md5"
     */
    public function testPropertyMd5()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
