<?php
/**
 * XpanFileSearch200ResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FunEngines\BaiduXpanApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * XPan NAS API
 *
 * API for accessing XPan NAS data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FunEngines\BaiduXpanApiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * XpanFileSearch200ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description XpanFileSearch200Response
 * @package     FunEngines\BaiduXpanApiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class XpanFileSearch200ResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "XpanFileSearch200Response"
     */
    public function testXpanFileSearch200Response()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "has_more"
     */
    public function testPropertyHasMore()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "list"
     */
    public function testPropertyList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
