<?php
/**
 * DefaultApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  FunEngines\BaiduXpanApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * XPan NAS API
 *
 * API for accessing XPan NAS data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace FunEngines\BaiduXpanApiClient\Test\Api;

use \FunEngines\BaiduXpanApiClient\Configuration;
use \FunEngines\BaiduXpanApiClient\ApiException;
use \FunEngines\BaiduXpanApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  FunEngines\BaiduXpanApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiCategoryinfo
     *
     * 获取分类文件总个数.
     *
     */
    public function testApiCategoryinfo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiQuota
     *
     * 获取网盘容量信息.
     *
     */
    public function testApiQuota()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pcsSuperfile2Upload
     *
     * 分片上传.
     *
     */
    public function testPcsSuperfile2Upload()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xpanFileBtlist
     *
     * 获取bt列表.
     *
     */
    public function testXpanFileBtlist()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xpanFileCreate
     *
     * 创建文件, 创建文件夹.
     *
     */
    public function testXpanFileCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xpanFileDoclist
     *
     * 获取文档列表.
     *
     */
    public function testXpanFileDoclist()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xpanFileFilemanager
     *
     * 管理文件.
     *
     */
    public function testXpanFileFilemanager()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xpanFileImagelist
     *
     * 获取图片列表.
     *
     */
    public function testXpanFileImagelist()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xpanFileList
     *
     * 获取文件列表.
     *
     */
    public function testXpanFileList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xpanFilePrecreate
     *
     * 预上传.
     *
     */
    public function testXpanFilePrecreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xpanFileSearch
     *
     * 搜索文件.
     *
     */
    public function testXpanFileSearch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xpanFileVideolist
     *
     * 获取视频列表.
     *
     */
    public function testXpanFileVideolist()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xpanMultimediaCategorylist
     *
     * 获取分类文件列表.
     *
     */
    public function testXpanMultimediaCategorylist()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xpanMultimediaFilemetas
     *
     * 查询文件信息.
     *
     */
    public function testXpanMultimediaFilemetas()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xpanMultimediaListall
     *
     * 递归获取文件列表.
     *
     */
    public function testXpanMultimediaListall()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for xpanNasUinfo
     *
     * 获取用户信息.
     *
     */
    public function testXpanNasUinfo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
